# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://paulbuchanant9.com
baseurl: /
title: Paul Buchanan
playstation: Faze_Pa978ul
author: Paul Buchanan
description: Personal blog and resume
facebook: paul.buchanan.718
instagram: paulbuchanant9
avatar: profile3.jpg
youtube: UCbRHcCtFdXzdV5WOnrpU_TQ
email: paulbuchanant9@gmail.com
github: pa978ul 
twitter: paulbuchanant9
stackoverflow: users/11370554/paul-buchanan   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
